//
//  FeedListWireframe.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(type: .feed)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: FeedListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = FeedListInteractor()
        let presenter = FeedListPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
    }

}

// MARK: - Extensions -

extension FeedListWireframe: FeedListWireframeInterface {

    func navigate(to option: FeedListNavigationOption) {
        switch option {
        case .detail(let feedContent):
            openFeedDetail(with: feedContent)
        }
    }
}


extension FeedListWireframe {
    
    private func openFeedDetail(with feedContent: FeedContent) {
        if let split = viewController.splitViewController { 
            let controllers = split.viewControllers
            if split.isCollapsed {
                show(FeedDetailWireframe(feedContent: feedContent), with: .push, animated: true)
            } else {
                if let detailNavigation = controllers[SplitFeedComponents.detail.index] as? UINavigationController,
                    let detailViewController = detailNavigation.topViewController as? FeedDetailViewController {
                    detailViewController.feedContent = feedContent
                }
            }
        } else {
            show(FeedDetailWireframe(feedContent: feedContent), with: .push, animated: true)
        }
    }
    
}
