//
//  FeedListWireframe.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(type: .feed)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: FeedListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = FeedListInteractor()
        let presenter = FeedListPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension FeedListWireframe: FeedListWireframeInterface {

    func navigate(to option: FeedListNavigationOption) {
    }
}
