//
//  FeedListInteractor.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FeedListInteractor {
    var presenter: FeedListPresenterInteractorInterface?
    fileprivate let feedService = FeedService()
}

// MARK: - FeedListInteractorInterface

extension FeedListInteractor: FeedListInteractorInterface {

    func getFeed(page: Int) {
        feedService.get(page: page, { [weak self] result in
            self?._handleFeedResult(result)
        })
    }
    
}

// MARK: - Extensions

extension FeedListInteractor {
    
    private func _handleFeedResult(_ result: RequestResultType<Feed>) {
        switch result {
        case .success(let feed):
            self.presenter?.requestSuccess(feed)
            break
        case .failure(let errorResponse):
            self.presenter?.requestFailed(errorResponse)
            break
        }
    }
    
}
