//
//  FeedListPresenter.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedListPresenter {

    // MARK: - Private properties -

    private unowned var _view: FeedListViewInterface
    private var _interactor: FeedListInteractorInterface
    private var _wireframe: FeedListWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: FeedListWireframeInterface, view: FeedListViewInterface, interactor: FeedListInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension FeedListPresenter: FeedListPresenterInterface {
}
