//
//  FeedListInteractor.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FeedListInteractor {
    fileprivate let feedService = FeedService()
}

// MARK: - Extensions -

extension FeedListInteractor: FeedListInteractorInterface {
    
    func getFeeds(page: Int, completion: @escaping (RequestResultType<Feed>) -> Void) {
        feedService.get(page, completion)
    }
    
}
