platform :ios, '12.0'
use_frameworks!

def shared_pods
    
    pod 'Alamofire'
    pod 'TPKeyboardAvoiding'
    pod 'AlamofireImage'
    
end

target 'Vargo' do
    shared_pods
end

target 'VargoTests' do
    shared_pods
end

target 'VargoUITests' do
    shared_pods
end

# Workaround for Cocoapods issue
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
