//
//  FeedDetailPresenter.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedDetailPresenter {

    // MARK: - Private properties -

    private unowned var _view: FeedDetailViewInterface
    private var _interactor: FeedDetailInteractorInterface
    private var _wireframe: FeedDetailWireframeInterface
    
    private var _feedRelatedVideos: [FeedContent] = []

    // MARK: - Lifecycle -

    init(wireframe: FeedDetailWireframeInterface, view: FeedDetailViewInterface, interactor: FeedDetailInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - FeedDetailPresenterInterface -

extension FeedDetailPresenter: FeedDetailPresenterInterface {
    
    func setFeedDetailFromSplitViewController(_ feedContent: FeedContent) {
        
    }
    
    func didPressPlay() {
        
    }
    
    func didPressShare() {
        
    }
    
    func didPressBookmark() {
        
    }
    
    func didPressUrl() {
        
    }
    
    func numberOfSections() -> Int {
        return 1
    }
    
    func numberOfItems() -> Int {
        return _feedRelatedVideos.count
    }
    
    func didSelectItem(at indexPath: IndexPath) {
        guard let feedContent = _feedRelatedVideos[safeIndex: indexPath.item] else { return }
        _view.feedContent = feedContent
    }
    
    func item(at indexPath: IndexPath) -> FeedItemDetailInterface? {
        return _feedRelatedVideos[safeIndex: indexPath.item]
    }
    
    func loadRelatedVideos(_ relatedVideosPage: Int?) {
        _feedRelatedVideos = []
        if let page = relatedVideosPage {
            _view.showWaitingView(with: .loading)
            _interactor.getRelatedVideos(page: page)
        }
    }
    
}

// MARK: - FeedDetailPresenterInteractorInterface

extension FeedDetailPresenter: FeedDetailPresenterInteractorInterface {
    
    func requestSuccess(_ feed: [FeedContent]) {
        _feedRelatedVideos = feed
        _view.showWaitingView(with: .success)
        _view.reloadData()
        _view.scrollCollectionToFirstItem()
    }
    
    func requestFailed(_ error: ErrorResponse) {
        _view.showWaitingView(with: .error)
    }
    
}
