//
//  FeedDetailInterfaces.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol FeedDetailWireframeInterface: WireframeInterface { }

protocol FeedDetailViewInterface: ViewInterface {
    var feedContent: FeedItemDetailInterface? { get set }
}

protocol FeedDetailPresenterInterface: PresenterInterface {
    func didPressPlay()
    func didPressShare()
    func didPressBookmark()
    func didPressUrl()
    func numberOfSections() -> Int
    func numberOfItems() -> Int
    func didSelectItem(at indexPath: IndexPath)
    func item(at indexPath: IndexPath) -> FeedItemDetailInterface?
}

protocol FeedDetailInteractorInterface: InteractorInterface {
    
}

protocol FeedItemDetailInterface: FeedListItemInterface {
    var screenTitle: String { get }
    var authorTitle: String? { get }
    var author: String? { get }
    var urlTitle: String? { get }
    var urlDescription: String? { get }
    var url: String? { get }
    var date: String? { get }
}
