//
//  FeedDetailViewController.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class FeedDetailViewController: UIViewController {
    
    @IBOutlet weak var feedItemBookmarkButton: UIButton!
    
    @IBOutlet weak var feedItemImageView: VImageView!
    @IBOutlet weak var feedItemPlayerImageView: UIButton!
    
    @IBOutlet weak var feedItemDateLabel: UILabel!
    
    @IBOutlet weak var feedItemTitleLabel: UILabel!
    @IBOutlet weak var feedItemDescriptionLabel: UILabel!
    
    @IBOutlet weak var feedItemAuthorsTitleLabel: UILabel!
    @IBOutlet weak var feedItemAuthorsLabel: UILabel!
    
    @IBOutlet weak var feedItemFontTitleLabel: UILabel!
    @IBOutlet weak var feedItemUrlButton: UIButton!
    
    @IBOutlet weak var feedRelatedVideosContainerHeight: NSLayoutConstraint!
    @IBOutlet weak var feedRelatedVideosContainerBottom: NSLayoutConstraint!
    @IBOutlet weak var feedRelatedVideosContainer: UIView!
    @IBOutlet weak var collectionView: UICollectionView!
    
    @IBOutlet weak var feedRelatedVideosLoadingLabel: UILabel!
    @IBOutlet weak var feedRelatedVideosLoadingRetryButton: UIButton!
    @IBOutlet weak var feedRelatedVideosLoadingActivityIndicator: UIActivityIndicatorView!

    // MARK: - Public properties -

    var presenter: FeedDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension FeedDetailViewController: FeedDetailViewInterface {
}
