//
//  FeedDetailInteractor.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class FeedDetailInteractor {
    
}

// MARK: - Extensions -

extension FeedDetailInteractor: FeedDetailInteractorInterface {
    
}
