//
//  FeedDetailInterfaces.swift
//  Vargo
//
//  Created by Andre Souza on 22/10/2018.
//  Copyright (c) 2018 Andre Souza. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum FeedDetailNavigationOption {
}

protocol FeedDetailWireframeInterface: WireframeInterface {
    func navigate(to option: FeedDetailNavigationOption)
}

protocol FeedDetailViewInterface: ViewInterface {
}

protocol FeedDetailPresenterInterface: PresenterInterface {
}

protocol FeedDetailInteractorInterface: InteractorInterface {
}
